version: "3.8"

services:
    psqldb:
        image: postgres:15
        restart: unless-stopped
        env_file: ./todoapp-api/.env
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_DB: ${DB_NAME}
        ports:
            - ${DB_PORT}:5432
        volumes:
            - ./docker-data/db:/var/lib/postgresql/data
        networks:
            - backend

    todoapp-api:
        depends_on:
            - psqldb
        build: ./todoapp-api
        restart: unless-stopped
        env_file: ./todoapp-api/.env
        ports:
            - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
        environment:
            - CLIENT_ORIGIN=$CLIENT_ORIGIN
        networks:
            - backend
            - frontend

    todoapp-client:
        depends_on:
            - todoapp-api
        build:
            context: ./todoapp-client
            args:
                - REACT_APP_API_BASE_URL=$CLIENT_API_BASE_URL
        ports:
            - $REACT_LOCAL_PORT:$REACT_DOCKER_PORT
        networks:
            - frontend

volumes:
    db:

networks:
    backend:
    frontend:
