name: TodoApp API CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    lint:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x]

        defaults:
            run:
                working-directory: ./todoapp-api/

        name: Test changed-files
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: "2"

            - name: Get changed files in the todoapp-api folder
              id: changed-files-specific
              uses: tj-actions/changed-files@v35
              with:
                  files: todoapp-api/**

            - name: Run step if any file(s) in the todoapp-api folder change
              if: steps.changed-files-specific.outputs.any_changed == 'true'
              uses: actions/setup-node@v3
              with:
                node-version: ${{ matrix.node-version }}
                cache: "npm"
                cache-dependency-path: ./todoapp-api/package-lock.json
              run: npm ci
              run: npm run lint
              run: npm run format
