name: TodoApp API CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

env:
    DATABASE_URL: ${{ secrets.DATABASE_URL }}

jobs:
    dev:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x]

        defaults:
            run:
                working-directory: ./todoapp-api/

        name: TodoApp API CI
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: "2"

            - name: Get changed files in the todoapp-api folder
              id: changed-files-specific
              uses: tj-actions/changed-files@v35
              with:
                  files: todoapp-api/**

            - name: Setup node
              if: steps.changed-files-specific.outputs.any_changed == 'true'
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
                  cache-dependency-path: ./todoapp-api/package-lock.json

            - name: Install node dependencies
              if: steps.changed-files-specific.outputs.any_changed == 'true'
              run: npm ci

            - name: Run API Linter
              if: steps.changed-files-specific.outputs.any_changed == 'true'
              run: npm run lint

            - name: Run API Formatter
              if: steps.changed-files-specific.outputs.any_changed == 'true'
              run: npm run format

            - name: Run API Test
              if: steps.changed-files-specific.outputs.any_changed == 'true'
              run: npm run test:ci
