name: TodoApp Client CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    check:
        name: Check files
        outputs:
            run_job: ${{ steps.check_files.outputs.run_job }}
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v2
          with:
            fetch-depth: 2

    - name: check modified files
      id: check_files
      run: |
        echo "=============== list modified files ==============="
        git diff --name-only HEAD^ HEAD
      
        echo "========== check paths of modified files =========="
        git diff --name-only HEAD^ HEAD &gt; files.txt
        while IFS= read -r file
        do
            echo $file
            if [[ $file != todoapp-client/* ]]; then
                echo "This modified file is not under the 'todoapp-client' folder."
                echo "::set-output name=run_job::false"
                break
            else
                echo "::set-output name=run_job::true"
            fi
        done &lt; files.txt


todoapp_client:
    name: Job for 'todoapp-client' folder
    needs: check
    if: needs.check.outputs.run_job == 'true'
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x]

        defaults:
            run:
                working-directory: ./todoapp-client/

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v3
            with:
                node-version: ${{ matrix.node-version }}
                cache: "npm"
                cache-dependency-path: ./todoapp-client/package-lock.json
            - run: npm ci
            - name: Run API Linter
            run: npm run lint
            - name: Run API Formatter
            run: npm run format
