name: TodoApp Client CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    lint:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x]

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
                  cache-dependency-path: todoapp-client/package-lock.json
            - name: Run Client Linter
              working-directory: ./todoapp-client
              run: npm run lint
            - name: Run Client Formatter
              working-directory: ./todoapp-client
              run: npm run format
