name: Linter

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    lint:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x]

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
            - run: npm ci
              working-directory: ./todoapp-api
            - name: Run API linter
              working-directory: ./todoapp-api
              run: npm run lint
            - run: npm ci
              working-directory: ./todoapp-client
            - name: Run Client linter
              working-directory: ./todoapp-client
              run: npm run lint
